{{- if empty .Values.mikrotik.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mikrotik-dns-operator.configMapName" . }}
  labels:
    {{- include "mikrotik-dns-operator.labels" . | nindent 4 }}
type: Opaque
data:
  MIKROTIK_SSH_USERNAME: {{ .Values.mikrotik.credentials.username | b64enc | quote }}
  {{- if .Values.mikrotik.credentials.password }}
  MIKROTIK_SSH_PASSWORD: {{ .Values.mikrotik.credentials.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.mikrotik.credentials.privateKey }}
  MIKROTIK_SSH_PRIVATE_KEY: {{ .Values.mikrotik.credentials.privateKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.mikrotik.credentials.passphrase }}
  MIKROTIK_SSH_PASSPHRASE: {{ .Values.mikrotik.credentials.passphrase | b64enc | quote }}
  {{- end }}
{{- end }}