{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mikrotik-dns-operator.serviceAccountName" . }}
  labels:
    {{- include "mikrotik-dns-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "mikrotik-dns-operator.serviceAccountName" . }}
rules:
  - apiGroups: [networking.k8s.io]
    resources: [ingresses]
    verbs: [list, watch, get, patch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "mikrotik-dns-operator.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "mikrotik-dns-operator.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "mikrotik-dns-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
